/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.City;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author NetrA
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PatientDirectory pDirectory;
    City city;
    public MainJFrame() {
        initComponents();
        pDirectory = new PatientDirectory();
        city =new City();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnEncounterHistory = new javax.swing.JButton();
        btnOld = new javax.swing.JButton();
        btnDelPat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setPreferredSize(new java.awt.Dimension(1035, 300));

        controlPanel.setBackground(new java.awt.Color(255, 255, 255));
        controlPanel.setPreferredSize(new java.awt.Dimension(250, 600));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setForeground(new java.awt.Color(0, 102, 102));
        btnAdmin.setText("Create New Patient");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        btnFaculty.setForeground(new java.awt.Color(0, 102, 102));
        btnFaculty.setText("Entire Visit log");
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });
        controlPanel.add(btnFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 153, -1));

        btnStudent.setForeground(new java.awt.Color(0, 102, 102));
        btnStudent.setText("Check Abnormality");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        controlPanel.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 153, -1));

        btnEncounterHistory.setForeground(new java.awt.Color(0, 102, 102));
        btnEncounterHistory.setText("Encounter history");
        btnEncounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterHistoryActionPerformed(evt);
            }
        });
        controlPanel.add(btnEncounterHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        btnOld.setForeground(new java.awt.Color(0, 102, 102));
        btnOld.setText("Existing Patient");
        btnOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldActionPerformed(evt);
            }
        });
        controlPanel.add(btnOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 153, -1));

        btnDelPat.setForeground(new java.awt.Color(0, 102, 102));
        btnDelPat.setText("Delete Patient");
        btnDelPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPatActionPerformed(evt);
            }
        });
        controlPanel.add(btnDelPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 160, -1));

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Update Patient Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        controlPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setPreferredSize(new java.awt.Dimension(622, 600));
        workArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/NetrA/assignment-4-Netra-Awate/Vital.gif")); // NOI18N
        workArea.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 860, 420));

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 2133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
       // CreateJPanel createpanel = new CreateJPanel(history);
        NewPatientJPanel graphpanel = new NewPatientJPanel(pDirectory,city);
        splitPane.setRightComponent(graphpanel);
        
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        AllPatientLogJPanel facultypanel = new AllPatientLogJPanel(pDirectory,city);
        splitPane.setRightComponent(facultypanel);
        
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
         AbnormalJPanel graphpanel = new AbnormalJPanel(pDirectory,city);
       splitPane.setRightComponent(graphpanel);
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldActionPerformed
        // TODO add your handling code here:
         OldPatientPanel graphpanel = new OldPatientPanel(pDirectory,city);
       splitPane.setRightComponent(graphpanel);
    }//GEN-LAST:event_btnOldActionPerformed

    private void btnEncounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterHistoryActionPerformed
        // TODO add your handling code here:
       // EncounterHistoryJPanel ehpanel = new EncounterHistoryJPanel(history);
        EncounterHistoryJPanel a = new EncounterHistoryJPanel(pDirectory,city);
        splitPane.setRightComponent(a);
    }//GEN-LAST:event_btnEncounterHistoryActionPerformed

    private void btnDelPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPatActionPerformed
        DeletePatient dp= new DeletePatient(pDirectory,city);
        splitPane.setRightComponent(dp);
    }//GEN-LAST:event_btnDelPatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       EditPatient ep= new EditPatient(pDirectory,city);
         splitPane.setRightComponent(ep);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDelPat;
    private javax.swing.JButton btnEncounterHistory;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnOld;
    private javax.swing.JButton btnStudent;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
